version: '3.9'

name: gleam-backend-container

services:
  db:
    image: postgres
    container_name: inthackathon-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: inthackathon-db
