version: '3.8'
services:
  dev-db:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: inthackathon-db
    networks:
      - tawan-network


  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: tawan-docker
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - dev-db
  #   volumes:
  #     - ./src:/app/src

networks:
  tawan-network: